version: "3.8"
services:
  web:
    build:
      context: .
      args:
        UID: ${UID:-1000}
        GID: ${GID:-${UID:-1000}}
    ports:
      - "3004:3000"
    environment:
      - RAILS_MASTER_KEY=$RAILS_MASTER_KEY
      - REDIS_URL=$REDIS_URL
      - DATABASE_URL=$DATABASE_URL
    depends_on:
      redis-db:
        condition: service_started
      postgres-db:
        condition: service_healthy

  postgres-db:
    image: postgres
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: password
    volumes:
      - ./tmp/db:/var/lib/postgresql/data
    ports:
      - "5435:5432"
    healthcheck:
      test: pg_isready
      interval: 2s
      timeout: 5s
      retries: 30

  redis-db:
    image: redis

  sidekiq:
    image: opensnp/rails-sidekiq:latest
    command: bundle exec sidekiq
    environment:
      - RAILS_MASTER_KEY=$RAILS_MASTER_KEY
      - REDIS_URL=$REDIS_URL
      - DATABASE_URL=$DATABASE_URL
    depends_on:
      redis-db:
        condition: service_started
      postgres-db:
        condition: service_healthy
